### ISSUE TITLE
Review Backend and Frontend User Auth

### ISSUE THREAD

**Issue by cstinepham** [cstinepham/Petflix#2]
Live link for testing: [Petflix](https://pet-flix.herokuapp.com/#/)

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look exactly like the actual site
  * Add the 'hero' image so that it looks like Netflix's home page
  * Style the form inputs to look more like Netflix
  * Style errors to look more like Netflix
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)

Good job, address the unchecked items/comments, and then I'll close the issue!

**Comment by cstinepham** [comment]
Thanks for the review Liz! Will definitely work on more styling. One thing about Netflix's home page that is really annoying - it keeps changing between two views! It changes day by day, and even on different laptops (when I open netflix.com next to someone else, we get different home pages). I attached screenshots of the two views since I was confused on which one to finally implement, but I liked the one that has the gray cards on it more. (see urls on each screenshot that they are both netflix.com)

<img width="1275" alt="screen shot 2018-12-14 at 11 09 38 am" src="https://user-images.githubusercontent.com/7661167/50022505-3b98a380-ff91-11e8-8a5a-dc41854378ed.png">
<img width="1440" alt="screen shot 2018-12-11 at 10 47 27 pm" src="https://user-images.githubusercontent.com/7661167/50022513-43584800-ff91-11e8-9e67-0b01d9282f86.png">
